nistemfile: Handle exception when tagpy doesn't know file type.
When using opus, the demucs process works, but reading tags fails in
tagpy with:
```
ValueError: unable to find file type
```

This patch catches this and fixes conversion of opus files.